# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# HEROKU_APP_NAME and HEROKU_API_KEY set as
# environment variables in CircleCI dashboard
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    working_directory: ~/CSE442-Mental-Health-Project
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

orbs:
  heroku: circleci/heroku@0.0.5

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/node:jessie-browsers
#    steps:
#      - checkout
#      - run: mkdir test-reports
#      - run:
#          name: Download Selenium
#          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
#      - run:
#          name: Start Selenium
#          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
#          background: true


#version: 2
#jobs:
#  build:
#
#    # Primary container image where all commands run
#
#    docker:
#      - image: circleci/python:3.6.2-stretch-browsers
#        environment:
#          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
#
#    # Service container image
#
#      - image: circleci/postgres:9.6.5-alpine-ram
#
#    steps:
#      - checkout
#      - run: sudo apt-get update
#      - run: sudo apt-get install postgresql-client-9.6
#      - run: whoami
#      - run: |
#          psql \
#          -d $TEST_DATABASE_URL \
#          -c "CREATE TABLE test (name char(25));"
#      - run: |
#          psql \
#          -d $TEST_DATABASE_URL \
#          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
#      - run: |
#          psql \
#          -d $TEST_DATABASE_URL \
#          -c "SELECT * from test"