# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# HEROKU_APP_NAME and HEROKU_API_KEY set as
# environment variables in CircleCI dashboard
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    working_directory: ~/CSE442-Mental-Health-Project
    steps:
      - checkout
      # Caching dependencies, installing using pip from requirements.
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      # Selenium Testing
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run:
          command: python tests/test_ub_mental_health_auth.py
#      - run:
#          name: Download Selenium
#          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
#      - run:
#          name: Start Selenium
#          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
#          background: true
      # Testing Begins
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr


  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

orbs:
  heroku: circleci/heroku@0.0.5

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
