"""empty message

Revision ID: 6347cc5e459c
Revises: 16d6fb9e46c1
Create Date: 2019-04-29 00:16:47.550240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6347cc5e459c'
down_revision = '16d6fb9e46c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('achievement1', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement10', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement2', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement3', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement4', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement5', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement6', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement7', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement8', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('achievement9', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'achievement9')
    op.drop_column('user', 'achievement8')
    op.drop_column('user', 'achievement7')
    op.drop_column('user', 'achievement6')
    op.drop_column('user', 'achievement5')
    op.drop_column('user', 'achievement4')
    op.drop_column('user', 'achievement3')
    op.drop_column('user', 'achievement2')
    op.drop_column('user', 'achievement10')
    op.drop_column('user', 'achievement1')
    # ### end Alembic commands ###
