"""empty message

Revision ID: 79e1b0eeb76a
Revises: 1fb4172f7c7d
Create Date: 2019-04-29 10:42:10.743506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e1b0eeb76a'
down_revision = '1fb4172f7c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'multiplier')
    # ### end Alembic commands ###
