"""empty message

Revision ID: 7b045daaf877
Revises: 4c69bb2ba8ac
Create Date: 2019-03-29 00:30:47.429652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b045daaf877'
down_revision = '4c69bb2ba8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    # ### end Alembic commands ###
