"""nuked

Revision ID: 990f8467998b
Revises: 
Create Date: 2019-05-08 11:43:50.360271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990f8467998b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('lastlogin', sa.Integer(), nullable=True),
    sa.Column('currstreak', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('achievement1', sa.Integer(), nullable=True),
    sa.Column('achievement2', sa.Integer(), nullable=True),
    sa.Column('achievement3', sa.Integer(), nullable=True),
    sa.Column('achievement4', sa.Integer(), nullable=True),
    sa.Column('achievement5', sa.Integer(), nullable=True),
    sa.Column('achievement6', sa.Integer(), nullable=True),
    sa.Column('achievement7', sa.Integer(), nullable=True),
    sa.Column('achievement8', sa.Integer(), nullable=True),
    sa.Column('achievement9', sa.Integer(), nullable=True),
    sa.Column('achievement10', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
