"""empty message

Revision ID: 9a6c178c3a3b
Revises: 990f8467998b
Create Date: 2019-05-08 12:02:01.023794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6c178c3a3b'
down_revision = '990f8467998b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quiz_taken', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quiz_taken')
    # ### end Alembic commands ###
